name:                roboservant
version:             0.1.0.0
github:              "mwotton/roboservant"
license:             BSD3
author:              "Mark Wotton, Samuel Schlesinger"
maintainer:          "mwotton@gmail.com"
copyright:           "2020 Mark Wotton, Samuel Schlesinger"
synopsis:            Automatic session-aware servant testing
category:            Web
description:         Please see the README on GitHub at <https://github.com/mwotton/roboservant#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

- QuickCheck
- bytestring
- containers
- hedgehog
- http-client
- http-media
- mtl
- quickcheck-state-machine >= 0.7
- servant >= 0.17
- servant-client >= 0.17
- servant-flatten
- servant-server >= 0.17
- string-conversions

# test deps
- hspec
- QuickCheck
- aeson

ghc-options: -Wall

library:
  source-dirs: src

tests:
  roboservant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roboservant
